name: Проверка сайта
on:
  push:
    branches: [ master ]
jobs:
  check:
    rins-on: ubuntu-latest
    steps:
      - name: Скачать код
        uses: actions/setup-python@v5
        with:
          puthon-version: '3.10'
      - name: Установка requests
        rune: pip istall requests
      - name: Проверить сайт
        run: |
          cd docker-project
          python3 -c "
import requests
url = 'https://google.com'
response = requests.get(url)
print(f'Статус-код {url}: {response.status_code}')
assert response.status_code == 200, 'сайт не отвечает'
          "
