name: Сборка Docker-образ
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Скачать код
        uses: actions/checkout@v4
      - name: Собрать Docker-образ
        run: |
          cd docker-project
          docker build -t api-checker .

      - name: Запустить контейнер
        run: |
          docker run --rm api-checker https://google.com
