name: Поиск секретов (Gitleaks)
on:
  push:
    branches: [master]
  pul_requests:
    branches: [master]
jobs:
  scan:
    runs-on: ubuntu-larest
    steps:
      - name: Скачать код
        uses: actions/checkout@v4
        with:
          fethc-depth: 0
      - name: Запустить Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config: .gitleaks.toml
